line-message:
  api_uri: "http://micro-volunteer-supporter.com:8000/v1/sns/send-request-volunteer"
  accept_button_uri: "http://micro-volunteer-supporter.com"
  ignore_button_uri: "http://micro-volunteer-supporter.com"
  accept_button_label: "いま行きます！"
  ignore_button_label: "今は無理"

encrypt:
  jwt:
    secret: 'MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAPfawZ1qJkJP2j+17nI38xgH9KQPFD1GnMfraazWsbTqlIgHCxcRezJX7G5sJfasitrwkbLv29BB4kvwN+vMro0CAwEAAQ=='
    expire: 5184000
  volunteerdb:
    key: 'MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAPfawZ1qJkJP2j+17nI38xgH9KQPFD1GnMfraazWsbTqlIgHCxcRezJX7G5sJfasitrwkbLv29BB4kvwN+vMro0CAwEAAQ=='
